<?php
/**	op-asset-bootstrap2:/template/admin.phtml
 *
 * @created    2025-07-09
 * @version    1.0
 * @package    op-asset-bootstrap2
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	...
$h1 = '<h1>The Admin IP has not been set.</h1>'.PHP_EOL;
$p  = '<p>Please edit this config file: <code>asset/config/admin.php</code></p>'.PHP_EOL;

//	...
echo OP()->isShell() ? strip_tags($h1) : $h1;
echo OP()->isShell() ? strip_tags($p)  : $p;
