<?php
/**	op-asset-bootstrap2:/template/apache2handler.phtml
 *
 * @created    2025-07-09
 * @version    1.0
 * @package    op-asset-bootstrap2
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	Calc rewrite base.
$rewrite_base = str_replace($_SERVER['DOCUMENT_ROOT'], '/', $_SERVER['SCRIPT_FILENAME']);
$rewrite_base = dirname($rewrite_base);
$rewrite_base = trim($rewrite_base,'/');
$rewrite_base = $rewrite_base ? "/{$rewrite_base }/": '/';

?>
<h1>Bootstrap: <?= PHP_SAPI ?></h1>
<ol>
	<li>Open .htaccess: `vim .htaccess`</li>
	<li>
		Edit .htaccess
		<ol>
			<li>Change to `RewriteEngine` value: `On` from `Off`.</li>
			<li>Change to `RewriteBase` value: `<?= $rewrite_base ?>`</li>
		</ol>
	</li>
	<li>Reload this page.</li>
</ol>
