<?php
/**	op-asset-bootstrap2:/template/apache2handler.phtml
 *
 * @created    2025-07-09
 * @version    1.0
 * @package    op-asset-bootstrap2
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

//	Calc rewrite base.
$rewrite_base = str_replace($_SERVER['DOCUMENT_ROOT'], '/', $_SERVER['SCRIPT_FILENAME']);
$rewrite_base = dirname($rewrite_base);
$rewrite_base = trim($rewrite_base,'/');
$rewrite_base = $rewrite_base ? "/{$rewrite_base }/": '/';

?>
<h1>Bootstrap: <?= PHP_SAPI ?></h1>
<ol>
	<li>Move to following directory: <code><?= OP()->Path('app:/') ?></code></li>
	<li>Open .htaccess: <code>vim .htaccess</code></li>
	<li>
		Edit .htaccess:
		<ol>
			<li>Change of <code>RewriteEngine</code>: <code>Off</code> --&gt; <code>On</code>.</li>
			<?php if( $rewrite_base !== '/' ): ?>
			<li>Change of <code>RewriteBase</code>: <code>/</code> --&gt; <code><?= $rewrite_base ?></code></li>
			<?php endif; ?>
		</ol>
	</li>
	<li>Please reload this page.</li>
</ol>
