<?php
/**	op-asset-bootstrap2:/template/html.phtml
 *
 * @created    2025-07-09
 * @version    1.0
 * @package    op-asset-bootstrap2
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

/* @var $path string */
if( OP()->isShell() ){
	include($path);
	exit;
}

//	...
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/color.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/code.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/body.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/main.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/h.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/p.css');

?>
<html>
	<head>
	<!-- Style -->
	<style><?php OP()->Unit()->WebPack()->Output('css') ?></style>

	<!-- Title -->
	<title>ONEPIECE Framework</title>
	</head>
	<body>
		<header></header>
		<main>
			<?php
			if( file_exists($path) ){
				include($path);
			}else{
				echo "This file was not found: {$path}";
			}
			?>
		</main>
		<footer></footer>
	</body>
</html>
<?php
exit(__LINE__);
