<?php
/**	op-asset-bootstrap2:/template/html.phtml
 *
 * @created    2025-07-09
 * @version    1.0
 * @package    op-asset-bootstrap2
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All rights reserved.
 */

/**	namespace
 *
 */
namespace OP;

/* @var $path string */
if( OP()->isShell() ){
	include($path);
	exit(__LINE__);
}

//	...
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/color.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/code.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/body.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/main.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/h.css');
OP()->Unit()->WebPack()->Auto('asset:/webpack/css/p.css');

?>
<html>
	<head>
		<!-- Stylesheet -->
		<link type="text/css" href="https://2030.onepiece-framework.com/webpack/css/Translate.css" rel="stylesheet">

		<!-- JavaScript -->
		<script type="text/javascript" src="https://2030.onepiece-framework.com/webpack/js/Translate.js" defer></script>

	<!-- Style -->
	<style><?php OP()->Unit()->WebPack()->Output('css') ?></style>

	<!-- Title -->
	<title>ONEPIECE Framework</title>

	<style>
	a {
		color: var(--color-a-text);
	}
	:root {
		--color-a-text: hsl( 210, 80%, 50%);
	}
	@media (prefers-color-scheme: dark) {
		:root {
		--color-a-text: hsl( 210, 80%, 80%);
		}
	}
	</style>

	</head>
	<body>
		<header></header>
		<main>
			<div data-translation="true">
			<?php
			if( file_exists($path) ){
				include($path);
			}else{
				echo "This file was not found: {$path}";
			}
			?>
			</div>
		</main>
		<aside style="margin: 0 1em;">
			<hr/>
			<div id="op-translate-language-area"></div>
		</aside>
		<footer></footer>
	</body>
</html>
<?php
exit(__LINE__);
