<?php
/**	op-asset-bootstrap2:/template/html.phtml
 *
 * @created    2025-07-09
 * @version    1.0
 * @package    op-asset-bootstrap2
 * @author     Tomoaki Nagahara
 * @copyright  Tomoaki Nagahara All right reserved.
 */

/**	namespace
 *
 */
namespace OP;

/* @var $path string */

?>
<html>
	<head>
	</head>
	<body>
		<header></header>
		<main>
			<?php
			if( file_exists($path) ){
				include($path);
			}else{
				echo "Does not found this file: {$path}";
			}
			?>
		</main>
		<footer></footer>
	</body>
</html>
<?php
exit(__LINE__);
